# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET build and deploy on master

on:
  push:
    branches: [ "!master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@v1
        id: create_tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          RELEASE_BRANCHES: ["master"]
      - name: publish_win_x64
        run: dotnet publish -r win-x64 -c Release --self-contained true -p:PublishReadyToRun=true && tar -czvf ISRORBilling_win-x64.tar.gz -C ./bin/Release/net7.0/win-x64/publish ./
      - name: publish_linux_x64
        run: dotnet publish -r linux-x64 -c Release --self-contained true -p:PublishReadyToRun=true && tar -czvf ISRORBilling_linux-x64.tar.gz -C ./bin/Release/net7.0/linux-x64/publish ./

      - name: Create Release
        uses: ncipollo/release-action@v1
        id: create_release
        with:
          artifacts: "ISRORBilling_linux-x64.tar.gz,ISRORBilling_win-x64.tar.gz"
          tag: ${{ steps.create_tag.outputs.new_tag }}
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ github.token }}
